#!/bin/bash

# SEO Updates Script
# Updates title tags and meta descriptions across all pages
# Date: December 13, 2025

echo "🎯 Starting SEO Updates..."
echo ""

# Color codes
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Backup before making changes
BACKUP_DIR="backup_seo_$(date +%Y%m%d_%H%M%S)"
echo "${YELLOW}Creating backup at $BACKUP_DIR...${NC}"
mkdir -p "$BACKUP_DIR"
cp index.html "$BACKUP_DIR/"
cp -r shortcuts/ "$BACKUP_DIR/"
cp -r pages/ "$BACKUP_DIR/"
echo "${GREEN}✓ Backup created${NC}"
echo ""

echo "${YELLOW}📝 Recommended SEO Updates:${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "HOMEPAGE (index.html)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Current Title:"
echo "  Keyboard Shortcuts 2025 | VS Code, Windows, Mac & More"
echo ""
echo "Recommended Title:"
echo "  ${GREEN}Keyboard Shortcuts Guide | FastShortcuts 2025${NC}"
echo ""
echo "Current Description:"
echo "  Master keyboard shortcuts for VS Code, IntelliJ, Windows, Mac & Chrome..."
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete keyboard shortcuts guide for developers and designers. VS Code, IntelliJ, Windows, Mac, Chrome, Photoshop & more. 700+ searchable shortcuts.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "VS CODE PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}VS Code Keyboard Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete VS Code keyboard shortcuts for Windows, Mac & Linux. Covers editing, debugging, navigation, refactoring, and more. Free searchable guide.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "INTELLIJ PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}IntelliJ IDEA Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete IntelliJ IDEA keyboard shortcuts for Windows, Mac & Linux. Java development, refactoring, debugging, navigation, and more. Free guide.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "CHROME PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}Chrome Keyboard Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete Google Chrome keyboard shortcuts for Windows, Mac & Linux. Tabs, bookmarks, DevTools, navigation, and more. Free searchable guide.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "WINDOWS PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}Windows Keyboard Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete Windows 11 keyboard shortcuts. System, window management, File Explorer, virtual desktops, and more. Essential shortcuts for productivity.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "MACOS PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}macOS Keyboard Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete macOS keyboard shortcuts. System, Finder, window management, Spotlight, Mission Control, and more. Essential shortcuts for Mac users.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "SUBLIME TEXT PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}Sublime Text Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete Sublime Text keyboard shortcuts for Windows, Mac & Linux. Multi-cursor, editing, navigation, search, and more. Free searchable guide.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PHOTOSHOP PAGE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Recommended Title:"
echo "  ${GREEN}Photoshop Keyboard Shortcuts | FastShortcuts 2025${NC}"
echo ""
echo "Recommended Description:"
echo "  ${GREEN}Complete Adobe Photoshop keyboard shortcuts for Windows & Mac. Tools, layers, selections, adjustments, and more. Essential shortcuts for designers.${NC}"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "${YELLOW}📋 Next Steps:${NC}"
echo ""
echo "1. Review the recommendations above"
echo "2. Read the full SEO analysis: docs/seo/SEO_ANALYSIS_AND_IMPROVEMENTS.md"
echo "3. Update title tags and meta descriptions manually or ask for automation"
echo "4. Create social media images (1200x630px for OG, 1200x600px for Twitter)"
echo "5. Add enhanced structured data (Organization, WebSite, FAQs)"
echo "6. Submit sitemap to Google Search Console"
echo ""
echo "${GREEN}✓ Backup saved to: $BACKUP_DIR${NC}"
echo ""
echo "🎯 Estimated improvements after implementation:"
echo "  • CTR: +15-25%"
echo "  • Organic Traffic: +30-50%"
echo "  • Rankings: +3-5 positions"
echo "  • Timeline: 2-4 weeks for initial results"
echo ""
